name: Config Update

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

env:
  CHOOSE_END: "10"
  CONFIG: "https://raw.githubusercontent.com/KerryJi/rules/main/cla.ini"
  CONFIG2: "https://raw.githubusercontent.com/KerryJi/rules/main/nodnsleak.ini"
  CONFIG3: "https://raw.githubusercontent.com/KerryJi/rules/main/sb_ruleset.ini"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Setup sing-box"
      env:
        SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.9.0/sing-box_1.9.0_linux_amd64.deb"
      run: |
          set -Eeuo pipefail
          wget -O sing-box.deb $SING_BOX_DEB_URL
          sudo dpkg -i sing-box.deb
    - name: Set up Python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests pyyaml
    - name: Run script
      run: python ../converter.py
      working-directory: ./rule/
    - name: Commit and push config.json
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add ./rule/*.json
        git add ./rule/*.srs

        # 检查是否有文件被修改
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update rules"
          git push
        fi
    - name: Run update script
      run: |
        curl -O https://gist.githubusercontent.com/KerryJi/${{ secrets.GIST_ID }}/raw/4266d9bfc314b6a2c4cbfc0d6e26647b3801d7c8/suburl.txt
        SUBSCRIPTION_URLS=$(paste -sd '|' suburl.txt)
        python3 update_subscription.py -s "${SUBSCRIPTION_URLS}" -c "${CONFIG}" -e "${CHOOSE_END}" -t "clash" -o "cla.yaml"
        # - python3 update_subscription_script.py -s "${SUBSCRIPTION_URLS}" -c "${CONFIG}" -e "${CHOOSE_END}" -t "singbox" -o "singbox.json"
        python3 update_subscription.py -s "${SUBSCRIPTION_URLS}" -c "${CONFIG2}" -e "${CHOOSE_END}" -t "clash" -o "cla2.yaml"
        # - python3 update_subscription_script.py -s "${SUBSCRIPTION_URLS}" -c "${CONFIG2}" -e "${CHOOSE_END}" -t "singbox" -o "singbox2.json"
        python3 update_subscription.py -s "${SUBSCRIPTION_URLS}" -c "${CONFIG3}" -e "${CHOOSE_END}" -t "singbox" -o "sb_ruleset.json"
    - name: Deploy
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id:  ${{ secrets.GIST_ID }}
        file_path: cla.yaml
        file_type: text
    - name: Deploy
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id:  ${{ secrets.GIST_ID }}
        file_path: cla2.yaml
        file_type: text
    - name: Deploy
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id:  ${{ secrets.GIST_ID }}
        file_path: sb_ruleset.json
        file_type: text