name: Download, Process, and Upload Artifact

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'Workflow file name or ID'
        required: true
        default: '9331184609'
      artifact_name:
        description: 'Name of the artifact to download'
        required: true
env:
  owner: "PuerNya"
  repo: "sing-box"

jobs:
  process-artifact:
    runs-on: ubuntu-latest

    - name: Download artifact from another repository
      uses: actions/download-artifact@v2
      with:
        repository: $owner/$repo
        workflow_run_id: ${{ github.event.inputs.workflow_run_id }}
        name: ${{ github.event.inputs.artifact_name }}
        path: ./downloaded_artifact

    - name: Unzip artifact
      run: |
        sudo apt-get install unzip -y
        unzip ./downloaded_artifact/${{ github.event.inputs.artifact_name }}.zip -d ./extracted_artifact

    - name: Re-compress to tar.gz
      run: |
        tar -czvf ${{ github.event.inputs.artifact_name }}.tar.gz -C ./extracted_artifact .

    - name: Upload artifact to this repository
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.inputs.artifact_name }}.tar.gz
        path: ${{ github.event.inputs.artifact_name }}.tar.gz